# Generated by Django 2.1.5 on 2019-01-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20190108_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='slug',
            field=models.SlugField(blank=True, max_length=360),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=360),
        ),
    ]
