# Generated by Django 2.1.5 on 2019-01-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20190110_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='slug',
            field=models.SlugField(blank=True, max_length=640),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=640),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(max_length=640),
        ),
    ]
