# Generated by Django 2.1.5 on 2019-01-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20190110_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(max_length=640, upload_to='images/%Y/%m/%d'),
        ),
    ]
