# Generated by Django 2.1.5 on 2019-01-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20190110_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='image',
            name='slug',
            field=models.SlugField(blank=True, max_length=360),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=360),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(max_length=360),
        ),
    ]
