# Generated by Django 2.1.5 on 2019-01-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_auto_20190110_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='total_favors',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
